### ISSUE TITLE
Vault-env error on version

### ISSUE THREAD

**Issue by Minivolk02** [bank-vaults/vault-env#81]
```
time="2023-08-06T18:44:29Z" level=info msg="received new Vault token" addr= app=vault-env path=k8s_test role=common.ft
time="2023-08-06T18:44:29Z" level=info msg="initial Vault token arrived" app=vault-env
time="2023-08-06T18:44:29Z" level=warning msg="container-secret/secret: Endpoint ignored these unrecognized parameters: [version]" app=vault-env
panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 1 [running]:
github.com/bank-vaults/vault-env/internal/injector.(*SecretInjector).readVaultPath(0xc0005a3880, {0xc00005201c, 0x32}, {0x15cc1ec, 0x2}, 0xec?)
        /usr/local/src/vault-env/internal/injector/injector.go:430 +0xa3d
github.com/bank-vaults/vault-env/internal/injector.(*SecretInjector).InjectSecretsFromVault(0xc0005a3880, 0xc00073fd80, 0xc00073fc40)
        /usr/local/src/vault-env/internal/injector/injector.go:290 +0x7f1
main.main()
        /usr/local/src/vault-env/main.go:281 +0x11a5
```

**Comment by sagikazarmark** [comment]
@Minivolk02 thanks for reporting this issue. We will look into it.

**Comment by ramizpolic** [comment]
Resolved in https://github.com/bank-vaults/internal/pull/141, thanks for reporting!
